### ISSUE TITLE
Turn off "Listening for notifications..."

### ISSUE THREAD

**Issue by metalaureate** [Opus10/django-pgpubsub#16]
Feature enhancement suggestion: I'm happily using this package thank you but would like to optionally turn off the "listening" message as it flood my logs. I don't see a way to do that.

**Comment by PaulGilmartin** [comment]
@metalaureate thanks for the feedback. Proper logging in general is something this package lacks. In fact that message is written by a simple `print` statement.
```
def listen(
    channels: Union[List[BaseChannel], List[str]]=None,
    recover: bool=False,
    poll_count: Union[None, int]=None,
):
    multiprocessing.set_start_method('fork', force=True)
    pg_connection = listen_to_channels(channels)
    if recover:
        process_stored_notifications(channels)
        process_notifications(pg_connection)
    poll_count = poll_count or float('inf')
    while poll_count:
        if select.select([pg_connection], [], [], 1) == ([], [], []):
            print('Listening for notifications...\n')
        else:
            try:
                process_notifications(pg_connection)
            except Exception as e:
                print(f'Encountered exception {e}')
                print('Restarting process')
                process = multiprocessing.Process(
                    target=listen, args=(channels,))
                process.start()
                raise
        poll_count -= 1
```

I would like to replace this with fully-fledged opt-in logging as is available in e.g. Celery. Until I have time to do that, perhaps I can simply change so that this message is printed only once when we start listening, and not continuously. Would that address your issue?

**Comment by metalaureate** [comment]
That would be great. 🙏

**Comment by PaulGilmartin** [comment]
@metalaureate I have made the fix I mentioned above. It can be found in v0.0.8. Let me know if that fixes your issue! https://pypi.org/project/django-pgpubsub/0.0.8/

**Comment by metalaureate** [comment]
Perfect thank you
