### ISSUE TITLE
Best way to easily install triggers when running pytest with --no-migrations?

### ISSUE THREAD

**Issue by baldurh** [Opus10/django-pgpubsub#68]
We have a relatively big django project with lots of migrations and we run our tests without migrations to speed things up. What would be the easiest way for us to run the necessary SQL commands on the test database before running the tests that depend on pgpubsub?

**Comment by PaulGilmartin** [comment]
@baldurh Thanks for your interest in the library and really cool to hear this is being used in a larger Django project. That's a good question and one I had not considered. It's more of a question about how django-pgtrigger works, rather than django-pgpubsub itself. I don't have an exact answer, but I'd imagine you'd want to follow the notes of https://django-pgtrigger.readthedocs.io/en/4.9.0/advanced_installation/, specifically the part "Manual installation, enabling, and disabling
" seems relevant. Hope this helps!

**Comment by baldurh** [comment]
Thanks @PaulGilmartin. This lead us to find the solution :)

**Comment by PaulGilmartin** [comment]
@baldurh Great to hear! If you ever have time to share some documentation on how you achieved it, I would love to add it to our docs.

**Comment by baldurh** [comment]
We basically used `call_command` from `django.core.management` to call `call_command("pgtrigger", "install")` in unit tests. We implemented that in a fixture. Sweet and simple 😊

**Comment by PaulGilmartin** [comment]
Beautiful!
